version: '3.8'
services:
    database:
        image: mongo
        restart: always
        volumes:
            - my_data:/data/db
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
        ports:
            - "3000:3000"

volumes:
    my_data:
